package suitespec

func init() {
	for _, name := range allNames {
		register(name)
	}
}

// allNames lists every registered suite. Keep in sync with suites.All() and config.FullSuites.
var allNames = []string{
	"models",
	"models_get",
	"chat_completions",
	"chat_completions_stream",
	"chat_completions_stream_usage",
	"chat_completions_logprobs",
	"chat_completions_json",
	"chat_completions_vision",
	"chat_completions_reasoning",
	"chat_completions_audio",
	"chat_completions_tools",
	"chat_completions_tools_stream",
	"chat_completions_multi_turn",
	"chat_completions_get",
	"chat_completions_list",
	"chat_completions_delete",
	"chat_completions_messages",
	"completions",
	"completions_stream",
	"embeddings",
	"embeddings_batch",
	"responses",
	"responses_stream",
	"responses_tools",
	"responses_tools_stream",
	"responses_json",
	"responses_get",
	"responses_delete",
	"responses_cancel",
	"responses_input_items",
	"responses_compact",
	"responses_input_tokens",
	"moderations",
	"images_generations",
	"images_edits",
	"images_variations",
	"audio_speech",
	"audio_transcriptions",
	"audio_transcriptions_stream",
	"audio_translations",
	"files",
	"uploads",
	"batches_create",
	"batches_get",
	"batches_cancel",
	"conversations",
	"vector_stores",
	"vector_store_files",
	"vector_store_file_batches",
	"realtime_client_secrets",
	"containers",
	"container_files",
	"videos",
	"skills",
	"skill_versions",
	"fine_tuning",
	"chatkit_sessions",
	"chatkit_threads",
	"assistants",
	"assistants_threads",
	"error_responses",
}